### ISSUE TITLE
is that same board

### ISSUE THREAD

**Issue by bekirbostanci** [EmanuelFeru/hoverboard-sideboard-hack-STM#2]
hi 
I bought a hoverboard and mainboard is not looks like same but i am not sure. Can I use this ? 
![WhatsApp Image 2020-06-22 at 13 19 21](https://user-images.githubusercontent.com/26343575/85276920-33c19580-b48b-11ea-840e-1de9062ce059.jpeg)
![WhatsApp Image 2020-06-22 at 12 23 59](https://user-images.githubusercontent.com/26343575/85276931-36bc8600-b48b-11ea-8e09-7ed85a6238d9.jpeg)

**Comment by KaanDemirkoparan** [comment]
Yes it is same. You can use it. 

You shouldn't use this repositorie's issue page for mainboard issues. It would be better to use (https://github.com/EmanuelFeru/hoverboard-firmware-hack-FOC/issues) this page for issues or questions about mainboard.

**Comment by bekirbostanci** [comment]
it is not working. st-link did'nt detect the board. 
thank you for your help.
